### PR TITLE
Fixed battery energy_full when it does not exist

### PR DESCRIPTION
**Pull request by frenata**
Initially the program failed on my computer with a divide by zero panic. When I went to figure out why, I saw that you were reading from the battery filenames "energy_full" and "energy_now" but I had "charge_full" and "charge_now".

A bit of reading turned up that both can shop up, so I added some checks in the code to verify that the specified files exist before reading them.

I left checking for "charge_now"/"charge_full" as else ifs so that a final else could be added if neither file exists.

Since I ended up copying the string "/sys/class/power_supply/" a bunch more times I decided I might as well declare it as a constant, and updated the earlier parts of the function as well. Likewise for name := batt.Name() in line 121.

My first time to fork and PR anything on github, so hopefully I've done this the proper way. Thanks for the program!

### CODE REVIEW

**Comment by schachmat** [comment]
Thanks for the report. Your fix however leaves a race condition. You should never check for the existence of a file and then open it based on the result. The right way is to try to open it and if it fails, you do evasive maneuvers so the fix should mainly focus on adding an else at [line 115](https://github.com/schachmat/gods/pull/1/files#diff-05b5c86e7341f8f5a623876cd59e0b97L115).

Fixing the `readval()` function could also incorporate that only "full" or "now" gets passed as `field` and `readval()` then first tries to read `powerSupply + name + "/" + "energy_" + field` and if it fails to read the file, it then tries `powerSupply + name + "/" + "charge_" + field`.

Probably initializing `enFull` to `1` instead of `0` should also be done for much older systems which have no support for the `/sys/class/power_supply` at all or the division by zero has to be caught with a `recover` statement.

**Comment by frenata** [comment]
It seemed easier at first blush to meddle with the the call to readVal() than the operation of the function itself, but that makes sense.

**Comment by frenata** [comment]
Pushed changes you suggested, making readVal() try to open each file in turn.

To your last comment, it doesn't look like that should ever occur, since if reading of the powersupply directory fails, the function immediately exits and prints an Error to the status, without ever having a chance to divide by zero.

I did add a final test at line 137-139 to check for the possibility that the powersupply and BAT0 directories were readable, but no readable files for the numbers were found in them. I checked that it worked by creating a random directory with an empty BAT0 in it, and pointing the powerSupply const to that, and instead of the panic the statusbar just prints Error.

(in your status-18 font, which I can't seem to get to work, but that's another story.)

**Comment by schachmat** [comment]
merged, thanks. I will probably change some implementation details in the near future.

**Pull request closed without merging**
